### PR TITLE
Enable GSSAPI_HEIMDAL for kerberos auth

### PR DESCRIPTION
**Pull request by gitdevmod**

### CODE REVIEW

**Comment by fichtner** [comment]
This won't work. We use LibreSSL/OpenSSL from ports and this is incompatible with GSSAPI_BASE. You also need to remove GSSAPI_NONE from the SET statement.

**Comment by gitdevmod** [comment]
ok, which version of GSSAPI is compatible with LibreSSL/OpenSSL from ports ?

**Comment by fichtner** [comment]
Both GSSAPI_HEIMDAL and GSSAPI_MIT, but I am unsure which one we should aim for... I have avoided this subject so far ;(

**Comment by gitdevmod** [comment]
https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/kerberos5.html give some informations about mit heidmal. I used the version from base because I can put password in file and use it with kinit command.

**Comment by gitdevmod** [comment]
From manual only heidmal (base and ports) allow password from file. I really do not know what is different between mit and heidmal.

**Comment by fichtner** [comment]
Merged, thanks! :)

**Pull request merged**
