### PR TITLE
add HAProxy 2.6 on OPNsense 23.1

### PR DESCRIPTION
**Pull request by fraenki**
required for https://github.com/opnsense/plugins/issues/3026

### CODE REVIEW

**Comment by fichtner** [comment]
my bad for not seeing this!

with the merge to master we need both plugins on 22.7 unfortunately

**Comment by fichtner** [comment]
let me handle the other thing. thanks!

**Comment by fraenki** [comment]
thanks :)

**Comment by fichtner** [comment]
@fraenki FYI, net/haproxy26 was branched and net/haproxy was updated to 2.7 -- I'm holding back on updating net/haproxy in your interest, but we should be switching to net/haproxy26 in 23.1.1 if you can find the time.


Cheers,
Franco

**Pull request merged**
