### PR TITLE
Add MULTIPATH to net/frr7

### PR DESCRIPTION
**Pull request by rootwyrm**
Addresses https://github.com/opnsense/plugins/issues/1913 by enabling MULTIPATH for `net/frr6` and `net/frr7`.

### CODE REVIEW

**Comment by mimugmail** [comment]
Hm, this also need Kernel tuning

https://forum.opnsense.org/index.php?topic=12815.0

**Comment by rootwyrm** [comment]
That information is wrong (and considering the real source of the claim, that is not even slightly surprising.)
You can test with my frr7 build [found here](https://dnpkg.turnoffdoh.com/pkg/production/amd64/11.3/All/frr7-7.3.1.txz)

Observe:
```
production/ports/default.make.conf: net_frr7_SET+=MULTIPATH

root@testdev:~ # fetch https://dnpkg.turnoffdoh.com/pkg/production/amd64/11.3/All/frr7-7.3.1.txz
root@testdev:~ # pkg install -y frr7-7.3.1.txz
root@testdev:~ # pkg info frr | grep MULTIPATH
        MULTIPATH      : on
root@testdev:~ # /usr/local/etc/rc.d/frr restart
Stopping bgpd.
Waiting for PIDS: 89981.
Stopping zebra.
Waiting for PIDS: 66247.
Checking zebra.conf
2020/07/09 17:23:14 warnings: ZEBRA: [EC 4043309110] Disabling MPLS support (no kernel support)
OK
Starting zebra.
2020/07/09 17:23:15 warnings: ZEBRA: [EC 4043309110] Disabling MPLS support (no kernel support)
Checking bgpd.conf
OK
Starting bgpd.
root@testdev: ~# vtysh 
testdev# sho ip bgp 
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed

*= 10.53.0.10/32    10.1.0.82                0             0 4200000053 i
*>                  10.1.0.83                0             0 4200000053 i
*= 10.53.0.11/32    10.1.0.82                0             0 4200000053 i
*>                  10.1.0.83                0             0 4200000053 i
```

Sure looks like working multipath to me.

**Comment by mimugmail** [comment]
I'd wait for 20.7 and merge after switch to frr7.

**Comment by rootwyrm** [comment]
Why are you going well out of your way to block and delay a low impact change that solves problems for users immediately? What purpose does this serve? What is your logic? **You didn't even bother to look at the patch, which is for 20.7.** 

So why do you not want anybody to have MULTIPATH?

**Comment by mimugmail** [comment]
Because it will change to 7 AND enable multipath. I have no concerns to add it with 20.7.2 or so. If you need it NOW I can build you a compatible binary ..

**Comment by mimugmail** [comment]
MULTIPATH will come earliest in FreeBSD13 if not getting backported:
https://reviews.freebsd.org/D26449

Also seems unstable in pfsense since they disabled it again:
https://redmine.pfsense.org/issues/9545

Seems to only work some people (or breaks for some)

**Comment by fichtner** [comment]
No need to keep this open for now.

**Comment by rootwyrm** [comment]
D26449 is completely and entirely unrelated and has nothing whatsoever to do with this. FRR implements ECMP internally and updates zebra tables as appropriate. 
I have tested extensively, and there are no issues. The translation of "issues with some scenarios" is invariably people configuring things incorrectly and not reading the documentation. Period. **There are no issues unless the user's configuration would be invalid for the routing protocol.** I've had BGP working for months and OSPF working for weeks.

This was an easy, low-risk improvement with thorough testing that could have and should have just been done months ago instead of picking a fight for no reason whatsoever.

**Comment by onedr0p** [comment]
I would like to bump this request. @rootwyrm thanks for all your help on putting this together, while the maintainers don't find this useful there's people out there that do.

**Comment by fichtner** [comment]
@mimugmail as the FRR plugin maintainer said no for the time being and I support his decision

**Comment by CuBiC3D** [comment]
As far as I can see @rootwyrm stated that ECMP implementation in FRR does not relate or depend on D26499, pfsense issue only mentions the kernel parameter which is not required. Just closing the issue/PR prevents an active discussion and investigation to keep things rolling forward - ECMP is essential nowadays since clustering repurposed it in balancing nodes using e.g. MetalLB or Calico.

**Comment by mimugmail** [comment]
Hm .. TBH .. I have not tested it. FRR setting multiple routes doesn't mean they will also traverse the kernel with both directions.
You can fairly see multiple paths inside routing protocol but nothing happens on kernel level. 
Also bdsrp project states it needs backports from 13:
https://bsdrp.net/documentation/examples/ecmp

**Comment by onedr0p** [comment]
I'm sure we can get some testing here in here if someone could build and publish it with some basic instructions for installing.

**Comment by mimugmail** [comment]
There you go:
http://opn-repo.routerperformance.net/frr7-7.4_4.txz

**Comment by onedr0p** [comment]
Looks like I might be missing something here, do I need to uninstall the package in opnsense before I apply this?

```sh
root@opnsense:~ # fetch http://opn-repo.routerperformance.net/frr7-7.4_4.txz
frr7-7.4_4.txz                                        2741 kB 1303 kBps    02s
```

```sh
root@opnsense:~ # pkg install -y frr7-7.4_4.txz
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
    frr7: 7.4_4

Number of packages to be installed: 1

The process will require 14 MiB more space.
[1/1] Installing frr7-7.4_4...
===> Creating groups.
Using existing group 'frr'.
Using existing group 'frrvty'.
===> Creating users
Using existing user 'frr'.
Extracting frr7-7.4_4: 100%
=====
Message from frr7-7.4_4:

--
Beware that remote control of frr7 daemons over TCP sockets is enabled by
default.
Use daemon flags in /etc/rc.conf to disable it if unneeded, for example:
zebra_flags="-P0"
ospfd_flags="-P0"

FRR's OSPF daemons tries to allocate big socket buffer, so generate warning
messages like:
"setsockopt_so_sendbuf: fd 6: SO_SNDBUF set to 1048576 (requested 8388608)"
To prevent such message kern.ipc.maxsockbuf can be increased:
sysctl kern.ipc.maxsockbuf=16777216

Error message "ifam_read() doesn't read all socket data" is under investigation
```

```sh
root@opnsense:~ # pkg info frr | grep MULTIPATH
pkg: No package(s) matching frr
```

**Comment by fichtner** [comment]
# pkg add -f http://opn-repo.routerperformance.net/frr7-7.4_4.txz

**Comment by onedr0p** [comment]
Sorry, I tried that and I get the same error:

```sh
root@opnsense:~ # pkg add -f http://opn-repo.routerperformance.net/frr7-7.4_4.txz
Fetching frr7-7.4_4.txz: 100%    3 MiB   1.4MB/s    00:02
Installing frr7-7.4_4...
package frr7 is already installed, forced install
===> Creating groups.
Using existing group 'frr'.
Using existing group 'frrvty'.
===> Creating users
Using existing user 'frr'.
Extracting frr7-7.4_4: 100%
=====
Message from frr7-7.4_4:

--
Beware that remote control of frr7 daemons over TCP sockets is enabled by
default.
Use daemon flags in /etc/rc.conf to disable it if unneeded, for example:
zebra_flags="-P0"
ospfd_flags="-P0"

FRR's OSPF daemons tries to allocate big socket buffer, so generate warning
messages like:
"setsockopt_so_sendbuf: fd 6: SO_SNDBUF set to 1048576 (requested 8388608)"
To prevent such message kern.ipc.maxsockbuf can be increased:
sysctl kern.ipc.maxsockbuf=16777216

Error message "ifam_read() doesn't read all socket data" is under investigation
```

**Comment by fichtner** [comment]
The install is definitely working... what are you suggesting is an error?

**Comment by onedr0p** [comment]
It doesn't seem like it?

```sh
root@opnsense:~ # pkg info os-frr | grep MULTIPATH
root@opnsense:~ # pkg info frr | grep MULTIPATH
pkg: No package(s) matching frr
```

```sh
root@opnsense:~ # pkg info os-frr
os-frr-1.21_3
Name           : os-frr
Version        : 1.21_3
Installed on   : Fri Apr  9 19:48:42 2021 EDT
Origin         : opnsense/os-frr
```

**Comment by onedr0p** [comment]
Ok, excuse my idiocracy. I have applied this and noticed that MULTIPATH is working as expected. There are other people I know who can test this as well. I'll get them to chime in. Thanks for all your help!

**Comment by fichtner** [comment]
Ok, great. If in doubt:

    # pkg info -d os-frr

:)

**Comment by mimugmail** [comment]
> Ok, excuse my idiocracy. I have applied this and noticed that MULTIPATH is working as expected. There are other people I know who can test this as well. I'll get them to chime in. Thanks for all your help!

Working that you see multiple gateways or working that you can see packets traversing in multiple directions for the same destination. As I said, I'm not against the addition, but when its in and not working, its a bug, right now its just missing feature. Happy for all testers

**Comment by onedr0p** [comment]
I can see multipath in the output of the my BGP net...

```
opnsense.devbu.io# sho ip bgp
BGP table version is 19, local router ID is 192.168.150.1, vrf id 0
Default local pref 100, local AS 64512
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*>i10.69.4.192/26   192.168.42.23                 100      0 i
*>i10.69.114.128/26 192.168.42.20                 100      0 i
*>i10.69.177.192/26 192.168.42.22                 100      0 i
*>i10.69.181.0/26   192.168.42.24                 100      0 i
*>i10.69.212.128/26 192.168.42.21                 100      0 i
*>i10.69.216.192/26 192.168.42.11                 100      0 i
*>i10.69.218.128/26 192.168.42.12                 100      0 i
*>i10.69.246.0/26   192.168.42.10                 100      0 i
*> 192.168.42.0/24  0.0.0.0                  0         32768 i
*=i192.168.69.0/24  192.168.42.12                 100      0 i
*=i                 192.168.42.22                 100      0 i
*=i                 192.168.42.20                 100      0 i
*=i                 192.168.42.23                 100      0 i
*=i                 192.168.42.11                 100      0 i
*=i                 192.168.42.24                 100      0 i
*>i                 192.168.42.10                 100      0 i
*=i                 192.168.42.21                 100      0 i
*>i192.168.69.100/32
                    192.168.42.20                 100      0 i
*=i                 192.168.42.24                 100      0 i
*=i192.168.69.101/32
                    192.168.42.22                 100      0 i
*>i                 192.168.42.20                 100      0 i
*>i192.168.69.105/32
                    192.168.42.21                 100      0 i
*=i192.168.69.115/32
                    192.168.42.24                 100      0 i
*>i                 192.168.42.21                 100      0 i
*>i192.168.69.130/32
                    192.168.42.23                 100      0 i
*>i192.168.69.140/32
                    192.168.42.23                 100      0 i
*>i192.168.69.180/32
                    192.168.42.24                 100      0 i
*>i192.168.69.216/32
                    192.168.42.10                 100      0 i
*>i192.168.69.220/32
                    192.168.42.20                 100      0 i

Displayed  19 routes and 29 total paths
```

**Comment by mimugmail** [comment]
And do you see multiple routes in Kernel via netstat -nr?

**Comment by onedr0p** [comment]
It doesn't appear so, by my table above I should be seeing the following in the below table?

```
192.168.69.100/32  192.168.42.20
192.168.69.100/32  192.168.42.24
```

```

**Comment by mimugmail** [comment]
Yes, there should be two, just like stated in the link with the lab. I had a similar situation with WireGuard when they changed Interface Type in last version. I saw the route in sh ip ospf route but there was no in kernel and nothing traversing

**Comment by onedr0p** [comment]
Well that's disappointing 😔 Really thought we were onto something here so I could get my Kubernetes pods properly load balanced over BGP.

**Comment by Diaoul** [comment]
Is there a way to track this feature request other than this closed PR?

**Comment by fichtner** [comment]
sure, add one with a nice description pointing to this previous discussion

we will be adopting FreeBSD 13 eventually so that moves into scope...

**Comment by AdSchellevis** [comment]
in the next RC it will be disabled by default (https://github.com/opnsense/core/commit/8c71359163ef31dd1b888757a65fba6dc880574d) as it will likely cause other issues when default gateways can overlap.

**Comment by onedr0p** [comment]
@AdSchellevis Any plans to make it configurable via the UI, or is this something that will need tweaking elsewhere?

**Comment by fichtner** [comment]
you can override it from tunables (net.route.multipath to 1) but early reports indicate this causes undefined behaviour on multi-wan setups.

**Pull request closed without merging**
