### PR TITLE
Working ARM configs for 20.7

### PR DESCRIPTION
**Pull request by nekoprog**
Updated several files to match with OPNsense 20.7 and FreeBSD 12.1
requirements

### CODE REVIEW

**Comment by nekoprog** [comment]
@fichtner this fixes are ready to merge. Successfully build all sets files.

**Comment by fichtner** [comment]
@nekoprog sorry to have kept you wanting... can you move your changes to 21.1 since 20.7 won't be supported beyond end of January?

**Comment by nekoprog** [comment]
Sure, will let you know when it's done

**Comment by bevobird** [comment]
Is it normal that it takes like 4-5 hours, and he is still not finished with the build ?

**Comment by fichtner** [comment]
Sure, with all the community requests for binary packages and plugins you are looking at what we build and maintain every day. :)

**Comment by bevobird** [comment]
Can you tell me how long it can take ? so like 8 hours or like this ?

**Comment by fichtner** [comment]
It depends on a lot of factors. Our nightly build on amd64 fast hardware takes about 6 hours from scratch https://nightly.opnsense.org/20.7/amd64/logs 

If we walk about arm here IDK whether it's cross-compile (not as fast as amd64 native but still ok) or native (can take more than 24 hours)

**Comment by nekoprog** [comment]
> Can you tell me how long it can take ? so like 8 hours or like this ?

Very long if you have under 6 core cpus, over 24 hours, and take even longer on make packages.

**Comment by nekoprog** [comment]
KIV, wait for 21.7

**Comment by nekoprog** [comment]
hi, sorry for late reply, lately i have a tight schedule on my farm, so don't have much spare time to resume this work before 21.7 release. but i will try to come here often and guide those who wants to resume my work.

**Comment by fichtner** [comment]
@nekoprog not a problem, thanks for all your work and see you soon :)

**Pull request closed without merging**
