### PR TITLE
build arm: fix bananapi.dtb file name

### PR DESCRIPTION
**Pull request by nekoprog**
Need to test bananapi image first from https://drive.google.com/drive/folders/1bAWuECNJwu0LdJOpaIn-2MrTKZ8evGNY. If it boots, this should be safe to merge. Else need to rename the copied bananapi.dtb too.

### CODE REVIEW

**Comment by fichtner** [comment]
Merged, thanks. I'll try to offer a bpi image very soon and help with testing.

**Comment by mimugmail** [comment]
I just check your version on GDrive and a fresh compiled image, both doesn't boot with BPI R1 or R2

**Comment by nekoprog** [comment]
Yep, it's only for bananapi, i don't which board, maybe the first model without any number. Because uboot also have bananapi2 and so on. Maybe @fichtner can show the device because he has one.

**Comment by fichtner** [comment]
next thing I'll do now that 19.1.7 is out...

**Comment by nekoprog** [comment]
If still not boot, it might need to use dd with the included .bin from u-boot-bananapi package. I noticed that all allwinner have a different way to boot into ubldr.

**Pull request merged**
