### PR TITLE
device: fix `boot1.sym: error: PHDR segment not covered by LOAD segment`

### PR DESCRIPTION
**Pull request by yrzr**
fix problem in https://github.com/opnsense/tools/issues/258

### CODE REVIEW

**Comment by fichtner** [comment]
I don't disagree but don't we need this for ports builds?

**Comment by yrzr** [comment]
@fichtner Yes, I believe so. Let me rebuild and test first.

**Comment by yrzr** [comment]
I have just finished a fresh native rebuild. As expected, it is safe to delete this on the native build.
On the other hand, cross-building takes much more time. Let's wait for the result.

**Comment by fichtner** [comment]
@yrzr how about moving it to MAKE_ARGS_DEV_CROSS using 
e6e97ed ?

**Comment by yrzr** [comment]
It would certainly work for native builds. But as I mentioned in https://github.com/opnsense/tools/issues/258, MAKE_ARGS_DEV_CROSS produces the same error in cross-builds. So I don't think this would solve the whole problem.

Moreover, I am cross-building without MAKE_ARGS_DEV_CROSS now. The kernel and base stages have been successfully made.  It is now working on the ports stage and has already produced about 289 packages. I guess it is also safe to remove MAKE_ARGS_DEV_CROSS on cross-builds. Let's wait for my final result.

**Comment by fichtner** [comment]
Ok, then consider me convinced we can remove them all. Let’s keep MAKE_ARGS_DEV_CROSS support for later. It might be useful still.

**Comment by yrzr** [comment]
Here is an update. I tried to cross-build as much as possible on AMD64 last week, without `CROSS_BINUTILS_PREFIX=/usr/local/aarch64-unknown-freebsd${SRCREVISION}/bin`.

As mentioned in https://github.com/opnsense/tools/issues/258#issuecomment-1039760120, `lang/go` fails in cross-builds. Therefore, I am forced to ignore some packages that rely on `lang/go`, such as `net-mgmt/telegraf`, `dnscrypt-proxy`, `net/wireguard` and etc. Apart from this problem, the building steps work well. I successfully get `base-22.1-aarch64.txz`, `kernel-22.1-aarch64.txz` and `packages-22.1-OpenSSL-aarch64.tar`.

Another problem is encountered when building the VM image. 

```bash
# make -C /usr/tools VERSION=22.1 DEVICE=ARM64 vm
......
>>> Begin extra: vm_hook
+ vm_hook /usr/obj/usr/tools/config/22.1/OpenSSL:aarch64/mnt
+ loader_conf_fixup /usr/obj/usr/tools/config/22.1/OpenSSL:aarch64/mnt
+ [ -f /usr/obj/usr/tools/config/22.1/OpenSSL:aarch64/mnt/usr/local/etc/rc.loader ]
+ chroot /usr/obj/usr/tools/config/22.1/OpenSSL:aarch64/mnt /usr/local/etc/rc.loader
chroot: /usr/local/etc/rc.loader: No such file or directory
*** Error code 1

Stop.
make: stopped in /usr/tools
```

I guess it is caused by chrooting into aarch64 environment without involving QEMU.

Therefore, I copied the mid-products to a native aarch64 build environment for VM image building. And everything works as expected.



So hereby I think we can finally come to this conclusion that`CROSS_BINUTILS_PREFIX=/usr/local/aarch64-unknown-freebsd${SRCREVISION}/bin` could be safely removed.

**Comment by fichtner** [comment]
ok for me but your pr has conflicts

**Comment by fichtner** [comment]
something went wrong so I merged this manually as 7680ca161a

**Pull request closed without merging**
